cliente=input("Pon el nombre del cliente:")
producto1=input("Pon el nombre del producto1:")
precio1=int(input("Pon el precio del producto1:"))
cantidad1=int(input("Pon la cantidad de productos1:"))
producto2=input("Pon el nombre del producto2:")
precio2=int(input("Pon el precio del producto 2:"))
cantidad2=int(input("Pon la cantidad de productos 2:"))
total=(precio1*cantidad1)+(precio2*cantidad2)
print(f"Con {cantidad1} {producto1} a {precio1} EUR y {cantidad2} {producto2} a {precio2} EUR, total {total} EUR.")