print("AULATEC | REGISTRO DE CLIENTES")
print("completa la ficha del nuevo cliente.")
nombre= input("Nombre: ")
correo= input("Correo electronico: ")
telefono= input("telefono: ")
print("\n-- Ficha Del CLIENTE ---")
print(f"nombre:{nombre}")
print(f"nombre:{correo}")
print(f"nombre:{telefono}")